Merge castholm/SDL@1b67d371a531ecb0499d4b80a865631c299f472a
* Updated to version 3.4.11 for development

* Fix web joystick vibration on Safari

(cherry picked from commit e0eb40f65f87bb10c7859695a33072bfaf3ac3ba)

* Fix web joystick vibration (again)

(cherry picked from commit 96c03dc66e89765d5f81123c2056706dd6f28ea7)

* workflows: Stop building for Steam Runtime 3 on arm64

The experimental Steam Linux Runtime 3.0 (arm64) container is being
phased out, so games that want native arm64 binaries should upgrade to
Steam Linux Runtime 4.0.

steamrt/tasks#1032

Signed-off-by: Simon McVittie <smcv@collabora.com>
(cherry picked from commit d834351d69c8567d09c0a036d48f4b6661ab5dc3)

* Handle java.util.ConcurrentModificationException while unregistering sensor listeners

We're still seeing this frequently when unregistering PlayStation controller sensors. We don't know what else is modifying the sensor list, but if we end up getting this exception we'll retry after a short sleep.

(cherry picked from commit 75270a426484ab8d3d2c9559745a09e6658f668a)

* Fixed java.lang.NullPointerException

From @AntTheAlchemist:
This is an interesting one, on a Xiaomi MiTV. Caused by a camera device, full stack:
android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args -> org.libsdl.app.HIDDeviceManager$1.onReceive -> handleUsbDeviceAttached -> connectHIDDeviceUSB -> getSerialNumber -> android.hardware.usb.UsbDevice.getSerialNumber -> android.hardware.usb.IUsbSerialReader$Stub.onTransact -> com.android.server.usb.UsbSerialReader.getSerial -> UsbUserPermissionManager.checkPermission -> hasPermission -> isCameraDevicePresent

(cherry picked from commit 42fc082b5ecb618dbd5eaca1a3466f659b3c427e)

* Fix java.lang.NoSuchMethodError: no static method "Lorg/libsdl/app/SDLActivity;.showFileDialog([Ljava/lang/String;ZZI)Z" on release build

* Enable extra player LED sets for PS5 Controllers

(cherry picked from commit 0c8feecce6e57a7a8c1b1eb06631e0a7a56fcd8f)

* Fix DirectInput POV handling for devices with extra hats

(cherry picked from commit 7341f04a12aa55ee1f412b0074284a41715b63bd)

* Add mappings for NES Switch controllers on Linux

(cherry picked from commit 2fd15d9e0d48afedd3f87795b9688560a6bdb7a4)

* Add PID for red octane games, as they support sony detection

(cherry picked from commit 205777210ece227427c524d191c78ca82b2dd335)

* Add GIP vids and pids for stage tour instruments (#15788)

(cherry picked from commit 3f80c0b82a5d19f8b324710acce8f68f368cb126)

* Respect SDL_HINT_JOYSTICK_MFI

(cherry picked from commit 0bd95b04307a42f09bb0f3baafc41bd353d6f280)

* SDL_hidapi_xbox360.c: Fix Y axis inversion on macOS (#15792)

Originally, macOS had opposite Y axis inversion as every other platform, likely to correct for an issue with the virtual gamepad reported by the old 360Controller driver.

Wired Xbox 360 controllers using native macOS drivers were first reported to be broken in https://github.com/libsdl-org/SDL/issues/11002.  The inversion was removed in https://github.com/libsdl-org/SDL/commit/7da728a642f2acfbba9543a3587363908d7aa1c3, presumably breaking 360Controller usage, but fixing wired 360 controller using the new native support in macOS 15 and above.  However, this change was reverted without explanation in https://github.com/libsdl-org/SDL/commit/d7b1ba1bfca7c9bf4f57075258ccfa0e0c6b2051 which added explicit support for the Steam Virtual Gamepad.  Presumably, Steam on macOS reports inverted Y axes to match what SDL expected on the platform.  However, this reversion broke the native macOS controller support.  The incorrect inversion also breaks using off-brand 360-class gamepads via the libusb backend of HIDRAW.

(cherry picked from commit 157c839139fbea8ff2b49a3e6a0637aef1346f57)

* Fixed the Xbox 360 Controller showing as a Steam Virtual Gamepad on macOS

(cherry picked from commit c62cc657a2ffb9e3658dce1c7800998495728a0e)

* Fixed a hang reading the Xbox report descriptor on macOS

(cherry picked from commit 64998d2bc8ec062186ba15978789b042ee831721)

* audio: Split device "zombie" status into multiple stages.

Otherwise, a device that is disconnected in the standard audio device thread
might keep failing WaitDevice() in a tight loop, each one generating a new
main thread callback. In normal situations, this is wasteful, but if the
app isn't pumping the event loop quickly (or at all!), this will quickly eat
up all the memory in a machine.

Now we note that the device is zombified right away, and device thread
iteration will use this to replace the implementation with the Zombie
equivalents once it owns the device lock.

The main thread callback will progress to device->zombie==2, which it uses to
decide if this is a duplicate disconnect notification. Since it also owns the
lock at this point, it takes the moment to set the Zombie implementation up,
too.

This allows things (like the WASAPI backend) to check for a non-zero zombie
state immediately without having to worry if the main thread callback ran, and
for the standard audio threads to also move to the Zombie implementation
without waiting on that callback.

(The Zombie implementation is used to make a dead device keep processing, so
things that need the audio device to make progress to function will keep
working, and things blindly pushing to an audio stream won't queue up endless
data that isn't being consumed.)

Fixes #15745.

(cherry picked from commit 61363588407195518c5fe0f3c99a3175f0fb85ed)

* Add Corsair as valid PS controller

(cherry picked from commit 14b0e9d922da78001223e563efd2f54f473a4115)

* don't fetch timestamp again

(cherry picked from commit ed43ec0277f9e31c43ad86297fcc80a80c59e5fa)

* ci: run GDK on older Windows environment
>
> The GDK version which is set up by build-scripts/setup-gdk-desktop.py does not support Visual Studio 2026

(cherry picked from commit 513b5d067d2eb5b14b80df64a97c2774f51cc8f1)

* Added support for Xbox controllers via libusb on macOS

A number of third party Xbox controllers are not supported by macOS, but work with libusb and the SDL HIDAPI driver.

(cherry picked from commit 18fc4d931a942e36f372218902b6319d113d0edd)

* Added hotplug detection when using libusb

Also switched to a single thread for libusb read operations instead of one thread per device

(cherry picked from commit 1475239328a0c9a48d35969f4e34023921c9d812)

* Fixed error C2440: 'function': cannot convert from 'int (__cdecl *)(libusb_context *,libusb_device *,libusb_hotplug_event,void *)' to 'libusb_hotplug_callback_fn'

(cherry picked from commit df294acbae42769e55f87613fddd1fabb8a5d378)

* EGL: Always pass the platform type when available

Always pass the EGL platform type for Wayland and X11, or the driver could potentially select the wrong backend if certain envvars are misconfigured.

(cherry picked from commit 34af24276f0c5777aa253fa5a73e6e3636922496)

* fix typos

(cherry picked from commit 65433383a6eff08e1927c67db44d1d810f89ceda)

* Don't modify the driver signature on the web

(cherry picked from commit 95dafa2bcd90ee20a1103a9b6b2456e8b7455f8f)

* Fix JoyCon pair type detection on the web

(cherry picked from commit 5e54decf531094a161ecd07d367f7673e6bdb1ab)

* Fix web crash for joystick without vibration

(cherry picked from commit 4a0d66116f956426c5b49860369c6d8b7787c98f)

* Fix Xbox One controller detection on the web

(cherry picked from commit 4f031ea5da370762469f977ee115a4d874d3de63)

* hidapi: fix function pointer type mismatch in backend table

The HIDAPI backend table used function pointers that didn't match the
macro-renamed backend function types, which trips Clang's function sanitizer.

Adding small wrappers so the backend table has the correct function types and
the cast to the backend-specific device type happens inside a direct call.
fixes #15821.

(cherry picked from commit 46d0ecead0f98c0987e86bb01a028f11bc7e5e77)

* Add normalized name for Emscripten joysticks

(cherry picked from commit 7bbd9d5c2c6925e5824de4288a1ed0bed0c0e5f7)

* SDL_joystick: add Austgame adapter to gamecube devices

"Austgame GameCube to USB converter" is an GameCube-to-USB adapter.

(cherry picked from commit 51e214a0124d5113e5d5378c9088b10bed96cb34)

* Fix the "redundant redeclaration" warning for `__debugbreak` when using MinGW (#14264)

(cherry picked from commit b0a9aa3db04128c9e66f8d958e08ea23ed88a951)

* doc: use testspriteminimal instead of testgles in android example

testgles depends on SDL_test so would need ../src/test/*.c as an additonal argument.

(cherry picked from commit da8aa39222221039a448054a66b713f5f30390c0)

* hidapi: do not enumerate XInput devices owned by a kernel driver via libusb on macOS

(cherry picked from commit cee2cb8ed1597697a4ce146e1ab7f1cefcf62081)

* Added SDL_HINT_ENABLE_STEAM_SCREEN_KEYBOARD

(cherry picked from commit c9b6581210597b46b3e5c7a4623af24bcbac1111)

* Sync SDL3 wiki -> header

[ci skip]

(cherry picked from commit ae429cf5ee6925775f3aeae712a198fdd5bfe530)

* Fix discrete Joy-Con mappings on Linux

(cherry picked from commit ca67f19c8f161cfff26ee52c57ff2ae8b9d42ef6)

* wayland: External windows are never hidden

Needed for the GPU renderer to function properly.

(cherry picked from commit dbfddb640952413fd26a3708cddb3b61e1682e65)

* wayland: Attach EGL objects to custom and external surfaces during reconfiguration

They are required when using EGL with an external surface.

(cherry picked from commit 06795b00ad7a51f13c5cc9393157680b7c7f186e)

* wikiheaders: Fix links in manpage generation.

Fixes #15665.

(cherry picked from commit 7134ed5c1c22f42c6938c4e7ecf5c2be57a6fcf6)

* examples/input/03-gamepad-polling: Render axes in blue.

It's easier to see against white than yellow was.

(cherry picked from commit d7e25c92c0af63d0548e311b6d1e433e9509583d)

* docs: warn not to destroy an SDL_AudioStream during its callback.

Fixes #15871.

(cherry picked from commit 0b692f64b034145382c0fb1eacafa6cd11aaf148)

* cmake: Print a warning if the libdecor development library is missing

libdecor is required for window decorations on Wayland when the toplevel decoration protocol is not supported, such as on GNOME and Weston. Warn if the development library can't be found, unless it was explicitly disabled.

(cherry picked from commit 607eb5206ee9c377c8f970e379ebc9db154c5bc4)

* keyboard: Limit text input event size for sdl2-compat

(cherry picked from commit 32f460d3570138c49772f3f37941f42a71b794c0)

* Add Void GENESIS controller support

Add AndGAMER/Void Gaming USB IDs for Void GENESIS.

Recognize the Void GENESIS SInput VID/PID pair and set its device name.
Add DirectInput gamepad mappings for the wired and dongle DirectInput modes.

(cherry picked from commit 111bb79bf82383fef003985536fd42b9037adb9f)

* Removed unnecessary assert in WIN_SetWindowOpacity()

Fixes https://github.com/libsdl-org/SDL/issues/15896

(cherry picked from commit f0e99e7c7f9aa90d5ce2e3b8a69f72c23faf257e)

* win32: Use the current cursor coordinates when processing WM_NCACTIVATE

The event coordinates returned by GetMessagePos() for WM_NCACTIVATE are out of date if the cursor moved while an overlay was active, and may indicate that the cursor is still in the window when it is not. Always use the current cursor coordinates when processing this message to avoid incorrectly setting mouse focus if the cursor is no longer within the window.

(cherry picked from commit 0a8ccb11ebc4d229adb8e5326a11bdc68e4022ac)

* Added a workaround for a crash in NVIDIA drivers when rendering YUV with Vulkan

Fixes https://github.com/libsdl-org/SDL/issues/13878

(cherry picked from commit e0b12bbcea659c5f60d7b1e7797902600b5a8a52)

* Fixes invalid dereference in animated cursor sort

`Wayland_CreateAnimatedCursor` calls `SDL_qsort` on an array of
type `**SDL_Surface`, not on an array of `*SDL_Surface`. As such the void
pointers in the callback need to be casted to `SDL_Surface **` not
`SDL_Surface *`.

This was likely not caught since it's very unlikely that reading a few
bytes past the end of this array results in reading unreadable memory,
so the only side effect was invalid sort results, which is a bit subtle.

I caught this because I build SDL with UBSAN enabled in my debug builds,
and it trapped when the multiplication of the garbage `SDL_Surface*`
width and heights overflowed. I validated that the change is correct by
adding logs (that have then since been removed) demonstrating that it
was previously comparing garbage, and is now comparing the actual cursor
surfaces.

(cherry picked from commit a168e96cbcf88f8b858b8d9f0c73819010634583)

* wayland: Fix incorrect dereference when sorting icon surfaces

(cherry picked from commit 2f1cf4629c9e76ec2999c8a348e4c55b46c0088d)

* Issue a batch when changing render targets in the Vulkan renderer

Otherwise we get rendering artifacts that look like drawing is being applied to the wrong render target

(cherry picked from commit 464b90b475f922ce038a926d497ecdb361b7e773)

* Get the physical device properties when using an external Vulkan device

Fixes `testffmpeg --sprites 100` when using the Vulkan renderer

(cherry picked from commit dfefce62e269532d45593349fe8af1bdc8b09a7b)

* audio: Pass the id, not the obj, to SDL_AudioDeviceDisconnected_OnMainThread.

If a device has disconnected, and the app has quit the audio subsystem before
the queued main thread function has run, the pointer will be bogus by the time
the run occurs. So now it looks up the object from its device ID, and if the
lookup returns NULL, it returns immediately and everything works out.

Reference Issue #14856.

(which might be fixed by this or not.)

(cherry picked from commit 774728b6fffd964a79ae7cc179372736a76a633f)

* Updated to version 3.4.12 for release

* Update for SDL 3.4.12

* Work around Zig x86_64 backend miscompile breaking -Dgpu_openxr=false

---------

Signed-off-by: Simon McVittie <smcv@collabora.com>
Co-authored-by: Sam Lantinga <slouken@libsdl.org>
Co-authored-by: Nintorch <92302738+Nintorch@users.noreply.github.com>
Co-authored-by: Simon McVittie <smcv@collabora.com>
Co-authored-by: Kadir <kadir_altindag@outlook.com>
Co-authored-by: Thad House <thadhouse1@gmail.com>
Co-authored-by: Zizin13 <162662805+Zizin13@users.noreply.github.com>
Co-authored-by: Sanjay Govind <sanjay.govind9@gmail.com>
Co-authored-by: QwertyChouskie <qwertychouskie@users.noreply.github.com>
Co-authored-by: Ryan C. Gordon <icculus@icculus.org>
Co-authored-by: Alejandro Perez <github.com.rtzzj@passmail.net>
Co-authored-by: expikr <77922942+expikr@users.noreply.github.com>
Co-authored-by: Anonymous Maarten <anonymous.maarten@gmail.com>
Co-authored-by: Frank Praznik <frank.praznik@gmail.com>
Co-authored-by: Brenton Bostick <bostick@gmail.com>
Co-authored-by: arnau.nau <a@rnau.me>
Co-authored-by: Pierre de La Morinerie <kemenaran@gmail.com>
Co-authored-by: Roman Fomin <rfomin@gmail.com>
Co-authored-by: tmkk <tmkkmac@gmail.com>
Co-authored-by: SDL Wiki Bot <icculus-sdlwikibot@icculus.org>
Co-authored-by: Vicki Pfau <vi@endrift.com>
Co-authored-by: Cameron Gutman <aicommander@gmail.com>
Co-authored-by: BZL <yu_gen_00@yahoo.co.jp>
Co-authored-by: Mason Remaley <mason@gamesbymason.com>
Co-authored-by: Carl Åstholm <carl@astholm.se>